cart/urls.py
from django.urls import path
from .views import add_to_cart, cart_detail, remove_from_cart, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('add/<int:item_id>/', add_to_cart, name='add_to_cart'),
    path('', cart_detail, name='cart_detail'),
    path('remove/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart-item/', update_cart_item, name='update_cart_item'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path("", include("logistics.urls")),
    path('orders/', include('order.urls')),
    path("inquiry/", include("inquiry.urls")),
    path("community/", include("community.urls")),
    path('cart/', include('cart.urls')),
    path("support/", include("support.urls")),
    path('favorites/', include('favorites.urls')),
    path('payments/', include('payments.urls')),
    path('follow/', include('follow.urls')),
    # 비밀번호 초기화
    path('accounts/password_reset/form', auth_views.PasswordResetView.as_view(), name="password_reset"), # 이메일 입력 화면
    path('accounts/password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"), # 이메일 발송 완료 화면
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), # 이메일 클릭 > 비밀번호 입력 화면
    path('accounts/password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),  # 비밀번호 초기화 완료 화면
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logistics/urls.py
from django.urls import path
from .views import AddProductView,ProductListView, UpdateProductView, ProductDetailView
from .views import DeleteProductDV, DeleteProductLV
from .views import CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from .views import MainListView, MainProductListView
from . import views

app_name  = 'logistics'
urlpatterns = [

    path('product/add/', AddProductView.as_view(), name='add_product'),
    path('product/list/', ProductListView.as_view(), name='product_list'),


    path('product/update/<int:pk>', UpdateProductView.as_view(), name='update_product'), 
    path('product/detail/<int:pk>', ProductDetailView.as_view(), name='product_detail'), 

    # 삭제
    path('product/delete/', DeleteProductLV.as_view(), name='del_list'),
    path('product/delete/<int:pk>/', DeleteProductDV.as_view(), name='del_product'),

    # customer 메인 페이지 : 카테고리별 상품리스트 조회
    path('', MainListView.as_view(), name='main'),
    path('categories/<int:pk>/', MainProductListView.as_view(), name='cat_products'),

    path('product/<int:product_id>/add_review/', views.add_review, name='add_review'),
]

cart/models.py
from django.db import models
from logistics.models import Product
from users.models import User

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Cart {self.id}"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.item.name}"

cart/views.py
from django.views.decorators.http import require_POST
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.urls import reverse
from logistics.models import Product
from .models import Cart, CartItem

def add_to_cart(request, item_id):
    item = get_object_or_404(Product, id=item_id)
    amount = int(request.POST.get('amount'))
    if request.user.is_authenticated:
        cart = Cart.objects.get(user=request.user)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, item=item)
        if not created:
            cart_item.quantity += amount
        else:
            cart_item.quantity = amount
        cart_item.save()
    else:
        cart = request.session.get('cart', {})
        cart[str(item_id)] = cart.get(str(item_id), 0) + amount
        request.session['cart'] = cart
    return redirect(reverse('cart:cart_detail'))

def cart_detail(request):
    cart_items = []
    if request.user.is_authenticated:
        cart = Cart.objects.get(user=request.user)
        items = CartItem.objects.filter(cart=cart)
        for item in items:
            cart_items.append({
                'id': item.id,
                'item': item.item,
                'quantity': item.quantity,
                'quantity_price': item.quantity * round(item.item.product_price * (1 - item.item.product_sale * 0.01)),
                'sales_price': round(item.item.product_price * (1 - item.item.product_sale * 0.01))
            })
    else:
        session_cart = request.session.get('cart', {})
        for item_id, quantity in session_cart.items():
            item = get_object_or_404(Product, id=item_id)
            cart_items.append({
                'item': item,
                'quantity': quantity,
                'quantity_price': quantity * round(item.product_price * (1 - item.product_sale * 0.01)),
                'sales_price': round(item.product_price * (1 - item.product_sale * 0.01))
            })
    total_price = sum(item['quantity_price'] for item in cart_items)
    return render(request, 'cart/cart_detail.html', {'cart_items': cart_items, 'total_price': total_price})

def remove_from_cart(request, item_id):
    item = get_object_or_404(Product, id=item_id)
    if request.user.is_authenticated:
        cart = Cart.objects.get(user=request.user)
        cart_item = get_object_or_404(CartItem, cart=cart, item=item)
        cart_item.delete()
    else:
        cart = request.session.get('cart')
        del cart[str(item_id)]
        request.session['cart'] = cart
    return redirect(reverse('cart:cart_detail'))

def transfer_session_cart_to_user(request, user):
    session_cart = request.session.get('cart', {})
    if not session_cart:
        return
    
    cart = Cart.objects.get(user=user)

    for item_id, quantity in session_cart.items():
        item = get_object_or_404(Product, id=item_id)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, item=item)
        if created:
            cart_item.quantity = quantity
        else:
            cart_item.quantity += quantity
        cart_item.save()

    del request.session['cart']

@require_POST
def update_cart_item(request):
    cart_item_id = request.POST.get('cart_item_id')
    quantity = request.POST.get('quantity')

    cart_item = get_object_or_404(CartItem, id=cart_item_id)
    cart_item.quantity = quantity
    cart_item.save()

    return JsonResponse({'success': True, 'quantity': cart_item.quantity})

cart/templates/cart/cart_detail.html
{% extends "customer_base.html" %}

{% block content %}

<h3>장바구니</h3>
{% if cart_items %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col"><input class="form-check-input me-1" type="checkbox" value="" id="selectAll"></th>
                <th scope="col">상품명</th>
                <th scope="col">가격</th>
                <th scope="col">수량</th>
                <th scope="col">주문 금액</th>
                <th scope="col">삭제</th>
            </tr>
        </thead>
        <tbody>
            {% for entry in cart_items %}
            <tr>
                <th scope="row"><input class="form-check-input me-1 checkbox" type="checkbox" value=""></th>
                <td style="width: 350px;" data-item-id="{{ entry.item.id }}"><a href="{% url 'logistics:product_detail' entry.item.id %}"><img src="{{ entry.item.product_img.url }}" alt="{{ entry.item.product_name }}" width="100" height="100">{{ entry.item.product_name }}</a></td>
                <td class="sales-price">{{ entry.sales_price }}</td>
                <td style="width: 160px;"><input type="number" value="{{ entry.quantity }}" min="1" data-cart-item-id="{{ entry.id }}" class="quantity-input form-control"></td>
                <td class="quantity-price">{{ entry.quantity_price }}</td>
                <td>
                    <form action="{% url 'cart:remove_from_cart' entry.item.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn-close" aria-label="Close"></button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- <p>Total: {{ cart.cartitem_set.all|length }} items</p> -->
    <p>총 금액 : <span id="total-price">0</span></p>
    <button id="order" class="btn btn-dark">주문</button>
{% else %}
    <p>Your cart is empty.</p>
{% endif %}
{% endblock %}

{% block scripts %}
<script>
document.addEventListener('DOMContentLoaded', function() {
    const selectAllCheckbox = document.getElementById('selectAll');
    const itemCheckboxes = document.querySelectorAll('.checkbox');
    const totalPriceElement = document.getElementById('total-price');


    selectAllCheckbox.addEventListener('change', function() {
        itemCheckboxes.forEach(function(checkbox) {
            // 한 개 선택되었을 때 전체 선택 클릭하면 금액이 중복 계산되는 문제 해결
            if (checkbox.checked == true && checkbox.checked == selectAllCheckbox.checked) {
                return;
            }
            checkbox.checked = selectAllCheckbox.checked;
            const row = checkbox.parentNode.parentNode;
            const itemPrice = parseFloat(row.querySelector('.quantity-price').innerText);
            if (checkbox.checked) {
                updateTotalPrice(itemPrice);
            } else {
                updateTotalPrice(-itemPrice);
            }
        });
    });

    itemCheckboxes.forEach(function(checkbox) {
        checkbox.addEventListener('change', function() {
            const row = checkbox.parentNode.parentNode;
            const itemPrice = parseInt(row.querySelector('.quantity-price').innerText);
            if (this.checked) {
                updateTotalPrice(itemPrice);
            } else {
                updateTotalPrice(-itemPrice);
            }
            const allChecked = Array.from(itemCheckboxes).every(function(checkbox) {
                return checkbox.checked;
            });
            selectAllCheckbox.checked = allChecked;
        });
    });
    
    function updateTotalPrice(itemPrice) {
        let totalPrice = parseInt(totalPriceElement.innerText);
        totalPrice += itemPrice;
        totalPriceElement.innerText = totalPrice;
    }
});

document.addEventListener('DOMContentLoaded', function() {
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie != '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                let cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    
    const csrfToken = getCookie('csrftoken');

    document.querySelectorAll('.quantity-input').forEach(function(input) {
        let beforeQuantity = input.value;
        input.addEventListener('change', function() {
            const cartItemId = this.getAttribute('data-cart-item-id');
            const quantity = this.value;
            const salesPrice = parseInt(this.closest('tr').querySelector('.sales-price').innerText);
            const quantityPriceCell = this.closest('tr').querySelector('.quantity-price');
            const totalPriceElement = document.getElementById('total-price');

            quantityPriceCell.innerText = parseInt(quantity) * salesPrice;
            
            if (this.closest('tr').querySelector('.checkbox').checked) {
                let totalPrice = parseInt(totalPriceElement.innerText);
                totalPrice = totalPrice - parseInt(beforeQuantity) * salesPrice + parseInt(quantity) * salesPrice;
                totalPriceElement.innerText = totalPrice;
            }
            beforeQuantity = quantity;

            const xhr = new XMLHttpRequest();
            xhr.open('POST', '{% url "cart:update_cart_item" %}', true);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            xhr.setRequestHeader('X-CSRFToken', csrfToken);

            xhr.onreadystatechange = function() {
                if (xhr.readyState === XMLHttpRequest.DONE) {
                    if (xhr.status === 200) {
                        const response = JSON.parse(xhr.responseText);
                        if (response.success) {
                            alert('수량이 변경되었습니다');
                        } else {
                            alert(response.error);
                        }
                    }
                }
            };

            xhr.send('cart_item_id=' + cartItemId + '&quantity=' + quantity);
        });
    });
});

document.getElementById('order').addEventListener('click', function() {
    let selectedRows = [];
    const checkboxes = document.querySelectorAll('.checkbox:checked');
    
    checkboxes.forEach(function(checkbox) {
        const row = checkbox.closest('tr');
        const rowData = {
            item_id: row.cells[1].getAttribute('data-item-id'),
            quantity: row.cells[3].querySelector('.quantity-input').getAttribute('value'),
            quantity_price: row.cells[4].innerText
        };
        selectedRows.push(rowData);
    });
    
    // 서버로 데이터 전송 (예: AJAX 요청)
    const xhr = new XMLHttpRequest();
    xhr.open('POST', '', true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.onreadystatechange = function() {
        if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
            // 성공적으로 서버로 전송되었을 때 수행할 작업
        }
    };
    xhr.send(JSON.stringify(selectedRows));
});

</script>
{% endblock %}