cart/urls.py
from django.urls import path
from .views import add_to_cart, cart_detail, remove_from_cart, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('add/<int:item_id>/', add_to_cart, name='add_to_cart'),
    path('', cart_detail, name='cart_detail'),
    path('remove/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart-item/', update_cart_item, name='update_cart_item'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path("", include("logistics.urls")),
    path('orders/', include('order.urls')),
    path("inquiry/", include("inquiry.urls")),
    path("community/", include("community.urls")),
    path('cart/', include('cart.urls')),
    path("support/", include("support.urls")),
    path('favorites/', include('favorites.urls')),
    path('payments/', include('payments.urls')),
    path('follow/', include('follow.urls')),
    # 비밀번호 초기화
    path('accounts/password_reset/form', auth_views.PasswordResetView.as_view(), name="password_reset"), # 이메일 입력 화면
    path('accounts/password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"), # 이메일 발송 완료 화면
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), # 이메일 클릭 > 비밀번호 입력 화면
    path('accounts/password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),  # 비밀번호 초기화 완료 화면
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordChangeDoneView
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'), # 로그인페이지
    path('store/', views.StoreDashboardView.as_view(), name='store_home'), # 스토어 메인페이지
    path('store/<int:store_id>/', views.CustomerStoreHomeView.as_view(), name='cus_store_home'), # 고객 기준 스토어 페이지
    path('customer/', views.customer_home, name='customer_home'), # 고객 마이페이지
    path('store/<int:store_id>/category/<int:category_id>/', views.CustomerStoreHomeView.as_view(), name='cus_store_home_cat'), # 고객 기준 스토어 페이지 - 카테고리
    path('signup/customer/', views.CustomerSignUpView.as_view(), name='customer_signup'), # 고객 회원가입 페이지
    path('signup/store/', views.StoreSignUpView.as_view(), name='store_signup'), # 스토어 회원가입 페이지
    path('signup/done/', views.SignUpDoneView.as_view(), name='signup_done'), # 회원가입 완료 페이지
    path('find_username/', views.find_username, name='find_username'), # 아이디 찾기
    path('logout/', views.logout_view, name='logout'), # 로그아웃
    path('edit/customer/', views.edit_customer, name='edit_customer'), # 고객 회원정보 수정 페이지
    path('edit/customer/done/', views.EditCustomerDoneView.as_view(), name='edit_customer_done'), # 고객 회원정보 수정 완료 페이지
    path('edit/store/', views.edit_store, name='edit_store'), # 스토어 회원정보 수정 페이지
    path('edit/store/done/', views.EditStoreDoneView.as_view(), name='edit_store_done'), # 스토어 회원정보 수정 완료 페이지
    path('edit/password/', views.edit_password, name='edit_password'), # 비밀번호 변경 페이지
    path('edit/password/done/', PasswordChangeDoneView.as_view(template_name='login_password/edit_password_done.html'), name='edit_password_done'), # 비밀번호 변경 완료 페이지
    path('delete/', views.account_delete, name='account_delete'), # 회원탈퇴
    path('delete/alert/', views.account_delete_alert, name='account_delete_alert'), # 회원탈퇴 안내 페이지
    path('delete/cancel', views.account_delete_cancel, name='account_delete_cancel'), # 탈퇴 취소
    path('delete/now', views.account_delete_now, name='account_delete_now'), # 즉시 탈퇴
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(unique=True) # 이메일
    is_customer = models.BooleanField(default=False) # 구매자 계정인지
    is_store = models.BooleanField(default=False) # 스토어 계정인지
    deactivetime = models.DateTimeField(null=True, blank=True) # 비활성화한 시간 

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='customer')
    cus_nickname = models.CharField(max_length=20) # 닉네임
    cus_name = models.CharField(max_length=20) # 이름
    cus_address = models.CharField(max_length=200) # 주소
    cus_zipcode = models.CharField(max_length=10) # 우편번호 - 수학적인 연산이 필요하지 않기에 CharField가 더 적절하다고 함
    cus_birth = models.DateField(blank=True) # 생년월일
    cus_telnum = models.CharField(max_length=20) # 전화번호
    cus_regdate = models.DateTimeField(auto_now_add=True) # 가입일 자동생성
    follows = models.ManyToManyField('self', symmetrical=False, related_name='followers', blank=True)

    def __str__(self) -> str:
        return self.cus_name

class Store(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='store')
    store_name = models.CharField(max_length=20) # 상호명
    store_img = models.ImageField(upload_to='store/img', null=True, blank=True) # 스토어 이미지
    store_num = models.CharField(max_length=20) # 사업자번호
    store_address = models.CharField(max_length=200) # 판매점 주소
    store_zipcode = models.CharField(max_length=10) # 판매점 우편번호 - 수학적인 연산이 필요하지 않기에 CharField가 더 적절하다고 함
    store_telnum = models.CharField(max_length=20) # 연락처
    store_regdate = models.DateTimeField(auto_now_add=True) # 가입일 자동생성

    def __str__(self) -> str:
        return self.store_name

users/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import *
from .models import User, Customer, Store
from logistics.models import Product
from community.models import Community
from .forms import CustomerSignUpForm, StoreSignUpForm, LoginForm, CustomerEditForm, StoreEditForm
from django.views.generic import CreateView, TemplateView, ListView
from django.contrib.auth import login, get_user_model, logout, authenticate, update_session_auth_hash
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.utils.translation import gettext as _
from django.utils import timezone
from django.core.paginator import Paginator
from django.core.exceptions import ObjectDoesNotExist
from cart.views import transfer_session_cart_to_user
from logistics.models import Product
from order.models import Order
from favorites.models import UserFavoriteStore
from cart.models import Cart
from .models import User, Customer, Store
from .forms import CustomerSignUpForm, StoreSignUpForm, LoginForm, CustomerEditForm, StoreEditForm
from .decorators import customer_required, store_required
from django.contrib.auth.models import AnonymousUser

User = get_user_model()

# Customer 회원가입
class CustomerSignUpView(CreateView):
    model = User
    form_class = CustomerSignUpForm
    template_name = 'customer/customer_signup.html' # Customer 회원가입 페이지로 이동

    def form_valid(self, form):
        user = form.save()
        Cart.objects.create(user=user)
        return redirect('users:signup_done')
    
# Store 회원가입
class StoreSignUpView(CreateView):
    model = User
    form_class = StoreSignUpForm
    template_name = 'store/store_signup.html' # Store 회원가입 페이지로 이동

    def form_valid(self, form):
        user = form.save()
        return redirect('users:signup_done')
    
# 회원가입 완료
class SignUpDoneView(TemplateView):
    template_name = 'login_password/signup_done.html'

# 로그인
class LoginView(auth_views.LoginView):

    form_class = LoginForm
    template_name = 'login_password/login.html'

    def dispatch(self, request, *args, **kwargs): 
        # 이미 로그인된 사용자가 login 페이지로 접근하면 logistics:main 페이지로 리다이렉트
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('logistics:main'))
        return super().dispatch(request, *args, **kwargs)

    def form_invalid(self, form):
        # 비활성화된 계정으로 로그인 시도 시, 탈퇴한 계정 페이지로
        username = form.cleaned_data.get('username')
        try:
            user = User.objects.get(username=username)
        except ObjectDoesNotExist:
            # messages.error(self.request, '아이디가 존재하지 않습니다.')
            return super().form_invalid(form)
        else:
            if user and not user.is_active:
                return HttpResponseRedirect(reverse('users:account_delete_alert'))
            return super().form_invalid(form)

    def get_success_url(self):
        user = self.request.user
        if user.is_authenticated:
            if user.is_customer: # 아이디가 Customer라면 logistics:main 페이지로
                # 세션의 정보 데이터베이스로 이동
                transfer_session_cart_to_user(self.request, user)
                return reverse('logistics:main')
            elif user.is_store: # 아이디가 Store라면 store_home 페이지로
                return reverse('users:store_home')
        else: # 잘못 입력하면 다시
            return reverse('login') 

# 로그아웃
def logout_view(request):
    logout(request)
    return redirect('users:login')  # 로그인 화면으로 리다이렉트


#--------------------------------
# 회원 탈퇴 - 실제 삭제가 아닌 비활성화 is_active = 0
@login_required
def account_delete(request):
    if request.method == 'POST':
        password = request.POST.get('password')
        user = authenticate(username=request.user.username, password=password)
        if user is not None:
            user_email = user.email  # 사용자 이메일 주소
            user.is_active = False # 탈퇴(비활성화) 처리
            user.deactivetime = timezone.now() # 비활성화 했을 당시의 시간을 저장
            user.save()
            logout(request)
            if hasattr(user, 'store'): # 만약 탈퇴하려는 계정이 판매자 계정이라면
                Product.objects.filter(store=user.store).update(is_active=False) # 해당 store의 상품들을 비활성화
            # 이메일 발송
            send_mail(
                subject='Desker에서 귀하의 계정 탈퇴를 확인합니다.',
                message=f"""안녕하세요, {user.username}님.
                            귀하의 Desker 계정이 성공적으로 탈퇴되었습니다.
                            이용해 주셔서 감사합니다. 더 나은 서비스로 다시 만날 수 있기를 바랍니다.
                            감사합니다,
                            Desker 팀""",
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user_email],
                fail_silently=False,
            )
            return redirect('users:login') # 탈퇴 후 로그인 페이지로 리다이렉트
        else:
            messages.error(request, '비밀번호가 틀렸습니다.')
            return render(request, 'account_delete/delete.html')
    return render(request, 'account_delete/delete.html')

# 탈퇴한 계정 페이지 - 회원탈퇴 해놓고 7일 이내 재 로그인시 표시(실제 로그인 처리되는것은 아니기에 last_login 시간에 반영 X)
def account_delete_alert(request):
    return render(request, 'account_delete/alert.html')

# 탈퇴 취소 페이지 - 탈퇴 취소됨 is_active = 1
def account_delete_cancel(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # 첫 진입 시 and 사용자가 아이디나 비밀번호를 입력하지 않았을 경우
        if not username or not password:
            messages.error(request, '탈퇴를 취소하려는 계정의 아이디와 비밀번호를 입력해주세요.')
            return render(request, 'account_delete/cancel.html')

        try:
            user = User.objects.get(username=username, is_active=False)
            if user.check_password(password): # 비밀번호가 일치하는 경우
                user.is_active = True # 사용자의 활성화 상태를 True로 설정
                user.deactivetime = None  # 비활성화 했던 시간을 None으로 변경

                # store 계정인 경우엔 상품들을 다시 활성화
                if hasattr(user, 'store') and user.store:
                    Product.all_objects.filter(store=user.store).update(is_active=True)
                user.save() 
                messages.success(request, '회원 탈퇴가 취소되었습니다. 계정이 활성화되었습니다.')
                return redirect('users:login')  # 로그인 페이지로 리다이렉트
            else:
                messages.error(request, '비밀번호가 일치하지 않습니다.') # 비밀번호가 일치하지 않으면
        except User.DoesNotExist:
            messages.error(request, '해당하는 계정을 찾을 수 없습니다.') # 아이디가 일치하지 않으면

    return render(request, 'account_delete/cancel.html')

# 즉시 탈퇴 페이지 - 즉시 DB에서 모든 정보 삭제
def account_delete_now(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # 첫 진입 시 and 사용자가 아이디나 비밀번호를 입력하지 않았을 경우
        if not username or not password:
            messages.error(request, '즉시 탈퇴하려는 계정의 아이디와 비밀번호를 입력해주세요.')
            return render(request, 'account_delete/now.html')

        try:
            user = User.objects.get(username=username)
            if user.check_password(password): # 비밀번호가 일치하는 경우
                if hasattr(user, 'store'): # store 계정인 경우 연결된 모든 상품 삭제
                    user.store.product_set.all().delete()   
                user.delete() # 계정 삭제
                messages.success(request, '계정이 성공적으로 삭제되었습니다.')
                return redirect('users:login')  # 로그인 페이지로 리다이렉트
            else:
                messages.error(request, '비밀번호가 일치하지 않습니다.') # 비밀번호가 일치하지 않으면
        except User.DoesNotExist:
            messages.error(request, '해당하는 계정을 찾을 수 없습니다.') # 아이디가 일치하지 않으면

    return render(request, 'account_delete/now.html')

#--------------------------------
# Customer 홈
@login_required
@customer_required
def customer_home(request):
    # 상품 목록 가져오기
    product = Product.objects.all()

    # 현재 로그인한 사용자의 커뮤니티 글 가져오기
    customer = request.user.customer 
    community_posts = Community.objects.filter(customer=customer)
    # merge
    orders = Order.objects.filter(customer=request.user.customer)
    customer = Customer.objects.get(user=request.user)
    
    context = {
        'products': product,
        'community_posts': community_posts, 
        'orders': orders,
        'favorites': customer.favorites.all(), 
        'followers': customer.followers.all(),
        'following': customer.follows.all()
    }
    return render(request, 'customer/customer_home.html', context)

# 아이디 찾기
def find_username(request):
    if request.method == 'POST':
        email = request.POST['email']
        users = User.objects.filter(email=email)
        if users.exists():
            current_site = get_current_site(request)
            domain = current_site.domain
            protocol = 'https' if request.is_secure() else 'http'
            user = users.first()
            login_url = reverse('users:login')  # 로그인 화면
            login_url = f"{protocol}://{domain}{login_url}"  # 전체 URL 생성
            # 이메일 문구
            send_mail(
                subject='Desker에서 귀하의 계정 정보를 안내드립니다.',
                message=f"""안녕하세요, Desker 입니다!
                            귀하의 계정 아이디는 다음과 같습니다: "{user.username}"
                            로그인 화면으로 이동하려면 다음 링크를 클릭하세요: {login_url}
                            Desker와 함께 더욱 효율적인 업무 환경을 만들어 가세요.
                            만약 이 메일이 잘못 전송되었다고 생각되시거나, 추가적인 도움이 필요하시면 언제든지 저희 고객 지원팀으로 연락 주시기 바랍니다.
                            감사합니다, 
                            Desker 팀""",
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[email],
                fail_silently=False,
            )
            return render(request, 'find/find_username_done.html')  # 이메일 발송 완료시 발송 완료 페이지로 이동
        else:

users/templates/account_delete/account_delete.html
{% extends "noncategory_base.html" %}

{% block content %}

<form method="POST" id="withdrawalForm">
    {% csrf_token %}
    <h2>회원 탈퇴</h2>
    <p>정말 탈퇴하시겠습니까?</p>
    <p>7일간 계정이 비활성화 상태가 되며 모든 정보는 DB에 저장됩니다.</p> 
    <p>7일 경과 후 자동으로 탈퇴됩니다.</p>
    <p>자동으로 탈퇴되기 전에 탈퇴 취소, 즉시 탈퇴를 할 수 있습니다.</p>
    <br>
    <p>판매자 계정은 비활성화 기간동안 모든 상품이 숨겨짐 처리되며 탈퇴 취소 시 복구됩니다.</p>
    <p>판매자 계정은 탈퇴 시, 숨겨졌던 모든 상품이 삭제됩니다.</p>
    <input type="password" name="password" placeholder="비밀번호를 입력해주세요" required>
    <div>
        <input type="checkbox" id="agree" name="agree">
        <label for="agree">위 내용을 모두 확인하였으며 회원탈퇴에 동의합니다.</label>
    </div>
    <input type="submit" value="탈퇴" disabled id="withdrawButton">
</form> 

{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<script>
    const form = document.getElementById('withdrawalForm');
    const checkBox = document.getElementById('agree');
    const withdrawButton = document.getElementById('withdrawButton');

    checkBox.addEventListener('change', function() {
        withdrawButton.disabled = !this.checked; // 체크박스의 상태 변경에 따라 버튼 활성화 혹은 비활성화
    });

    form.onsubmit = function(e) {
        e.preventDefault();  // 기본 제출 이벤트 방지
        if (!checkBox.checked) {
            alert('체크를 해주세요');  // 체크박스 미체크 시 얼럿
            return false;
        } else if (confirm('회원을 탈퇴합니다. 계속 진행하시겠습니까?')) {  // 체크박스 체크 시 확인 메시지 얼럿
            form.submit();  // 사용자 확인 후 양식 제출
        }
    };
</script> 

{% endblock %}

users/templates/account_delete/alert.html
{% extends "noncategory_base.html" %}

{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/delete.css' %}">
{% endblock %}

{% block content %}
<div class="title-container">
    <h2>회원 탈퇴한 계정입니다.</h2>
</div>

<div class="box">
    <div class="delete-text"> 
        <p> 이 계정은 회원 탈퇴일로부터 7일 후에 완전 삭제됩니다 </p>
        <p>회원 탈퇴를 취소하거나 지금 즉시 탈퇴하실 수 있습니다</p>
    </div>

    <form method="post" action="{% url 'users:account_delete_cancel' %}">
        {% csrf_token %}
        <button type="submit">탈퇴 취소하기</button>
    </form>

    <form method="post" action="{% url 'users:account_delete_now' %}">
        {% csrf_token %}
        <button type="submit">즉시 탈퇴하기</button>
    </form>
</div>


<a href="{% url 'users:login' %}" class="login-link">로그인 화면으로</a>

{% endblock %}
 

users/templates/account_delete/cancel.html
{% extends "noncategory_base.html" %}

{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/delete.css' %}">
{% endblock %}

{% block content %}

<div class="title-container">
    <h2>탈퇴 취소하기</h2>
</div>

<div class="box">
    <p>회원 탈퇴를 취소하고 계정이 활성화 됩니다.</p>
    <p>숨겨졌던 상품들이 다시 노출됩니다.</p>
    {% if messages %}
    <ul class="form-messages">
        {% for message in messages %}
        <li class="{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form method="post" action="{% url 'users:account_delete_cancel' %}" onsubmit="confirmDeleteCancel(event)">
        {% csrf_token %}
        <!-- 아이디 입력란 -->
        <input type="text" name="username" placeholder="아이디">
        <!-- 비밀번호 입력란 -->
        <input type="password" name="password" placeholder="비밀번호">
        <br>
        <br>
        <button type="submit">탈퇴 취소</button>
    </form>
</div>
<script>
    function confirmDeleteCancel(event) {
        // '회원 탈퇴를 취소하시겠습니까?' 안내 메시지
        const isConfirmed = confirm('회원 탈퇴를 취소하시겠습니까?');
        if (isConfirmed) {
            
        } else {
            // [아니오]를 선택했을 경우, 폼 제출을 중단
            event.preventDefault();
        }
    }
</script>
<a href="{% url 'users:login' %}" class="login-link">로그인 화면으로</a>

{% endblock %}

users/templates/account_delete/delete.html
{% extends "noncategory_base.html" %}

{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/profile_edit.css' %}">
{% endblock %}

{% block content %}
<div class="title-container">
    <h2>회원 탈퇴</h2>
</div>

<form method="POST" id="withdrawalForm">
    {% csrf_token %}
    <div class="delete-text"> 
        <p>정말 탈퇴하시겠습니까?</p>
        <p>7일간 계정이 비활성화 상태가 되며 모든 정보는 DB에 저장됩니다.</p> 
        <p>7일 경과 후 자동으로 탈퇴됩니다.</p>
        <p>자동으로 탈퇴되기 전에 탈퇴 취소, 즉시 탈퇴를 할 수 있습니다.</p>
        <br>
        <p>판매자 계정은 비활성화 기간동안 모든 상품이 숨겨짐 처리되며 탈퇴 취소 시 복구됩니다.</p>
        <p>판매자 계정은 탈퇴 시, 숨겨졌던 모든 상품이 삭제됩니다.</p>
    </div>
        {% if messages %}
    <ul class="form-messages">
        {% for message in messages %}
        <li class="{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <input type="password" name="password" placeholder="비밀번호를 입력해주세요" required>
    <div class="agreement-container">
        <input type="checkbox" id="agree" name="agree">
        <label for="agree">위 내용을 모두 확인하였으며 회원탈퇴에 동의합니다.</label>
    </div>
    <input type="submit" value="탈퇴" disabled id="withdrawButton">
</form> 

<script>
    const form = document.getElementById('withdrawalForm');
    const checkBox = document.getElementById('agree');
    const withdrawButton = document.getElementById('withdrawButton');

    checkBox.addEventListener('change', function() {
        withdrawButton.disabled = !this.checked; // 체크박스의 상태 변경에 따라 버튼 활성화 혹은 비활성화
    });

    form.onsubmit = function(e) {
        e.preventDefault();  // 기본 제출 이벤트 방지
        if (!checkBox.checked) {
            alert('체크를 해주세요');  // 체크박스 미체크 시 얼럿
            return false;
        } else if (confirm('회원을 탈퇴합니다. 계속 진행하시겠습니까?')) {  // 체크박스 체크 시 확인 메시지 얼럿
            form.submit();  // 사용자 확인 후 양식 제출
        }
    };
</script> 

{% endblock %}

users/templates/account_delete/now.html
{% extends "noncategory_base.html" %}

{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/delete.css' %}">
{% endblock %}

{% block content %}
<div class="title-container">
    <h2>즉시 탈퇴하기</h2>
</div>

<div class="box">
    <div class="delete-text">
        <p>즉시 탈퇴하고 모든 정보가 삭제 됩니다.</p>
        <p>숨겨진 상품들이 모두 삭제됩니다.</p>
    </div>
    {% if messages %}
    <ul class="form-messages">
        {% for message in messages %}
        <li class="{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <form method="post" action="{% url 'users:account_delete_now' %}" onsubmit="confirmDeleteNow(event)">
        {% csrf_token %}
        <!-- 아이디 입력란 -->
        <input type="text" name="username" placeholder="아이디" required>
        <!-- 비밀번호 입력란 -->
        <input type="password" name="password" placeholder="비밀번호" required>
        <br>
        <br>
        <button type="submit">계정 삭제</button>
    </form>
</div>
<script>
    function confirmDeleteNow(event) {
        // '회원 탈퇴를 취소하시겠습니까?' 안내 메시지
        const isConfirmed = confirm('즉시 탈퇴하시겠습니까?');
        if (isConfirmed) {
            
        } else {
            // [아니오]를 선택했을 경우, 폼 제출을 중단
            event.preventDefault();
        }
    }
</script>
<a href="{% url 'users:login' %}" class="login-link">로그인 화면으로</a>


{% endblock %}