cart/urls.py
from django.urls import path
from .views import add_to_cart, cart_detail, remove_from_cart, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('add/<int:item_id>/', add_to_cart, name='add_to_cart'),
    path('', cart_detail, name='cart_detail'),
    path('remove/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart-item/', update_cart_item, name='update_cart_item'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path("", include("logistics.urls")),
    path('orders/', include('order.urls')),
    path("inquiry/", include("inquiry.urls")),
    path("community/", include("community.urls")),
    path('cart/', include('cart.urls')),
    path("support/", include("support.urls")),
    path('favorites/', include('favorites.urls')),
    path('payments/', include('payments.urls')),
    path('follow/', include('follow.urls')),
    # 비밀번호 초기화
    path('accounts/password_reset/form', auth_views.PasswordResetView.as_view(), name="password_reset"), # 이메일 입력 화면
    path('accounts/password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"), # 이메일 발송 완료 화면
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), # 이메일 클릭 > 비밀번호 입력 화면
    path('accounts/password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),  # 비밀번호 초기화 완료 화면
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logistics/urls.py
from django.urls import path
from .views import AddProductView,ProductListView, UpdateProductView, ProductDetailView
from .views import DeleteProductDV, DeleteProductLV
from .views import CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from .views import MainListView, MainProductListView
from . import views

app_name  = 'logistics'
urlpatterns = [

    path('product/add/', AddProductView.as_view(), name='add_product'),
    path('product/list/', ProductListView.as_view(), name='product_list'),


    path('product/update/<int:pk>', UpdateProductView.as_view(), name='update_product'), 
    path('product/detail/<int:pk>', ProductDetailView.as_view(), name='product_detail'), 

    # 삭제
    path('product/delete/', DeleteProductLV.as_view(), name='del_list'),
    path('product/delete/<int:pk>/', DeleteProductDV.as_view(), name='del_product'),

    # customer 메인 페이지 : 카테고리별 상품리스트 조회
    path('', MainListView.as_view(), name='main'),
    path('categories/<int:pk>/', MainProductListView.as_view(), name='cat_products'),

    path('product/<int:product_id>/add_review/', views.add_review, name='add_review'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.display_orders_history, name='display_orders'),
    path('order/<int:pk>/', views.display_order, name='display_order'),
    path('order/<int:pk>/delete/', views.delete_order, name='delete_order'),
    path('order/', views.order, name='order'),
]

order/models.py
from django.db import models
from logistics.models import Product
from users.models import Customer

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    amount = models.IntegerField()
    price = models.IntegerField()
    address = models.CharField(max_length=100)

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from logistics.models import Product
from .models import Order
from django.contrib.auth.decorators import login_required
from users.decorators import customer_required

@login_required(login_url='users:login')
@customer_required
def order(request):
    if request.method == 'POST':
        # 해당 제품 가져오기
        product = Product.objects.get(id=request.POST.get('product'))
        amount = int(request.POST.get('amount'))
        # 재고 비교
        # 주문한 수량 >= 재고
        if amount <= product.product_inventory:
            product.product_inventory -= amount
            product.save()
            price = product.product_price * amount
            address = request.user.customer.cus_address
            data, created = Order.objects.get_or_create(product=product, customer=request.user.customer, address=address, defaults={'amount': amount, 'price': price})
            if not created:
                data.amount += amount
                data.price += price
            data.save()
            return render(request, 'order/order.html', {'status': '주문이 완료되었습니다.'})
        # 주문한 수량 < 재고
        else:
            
            return render(request, 'order/order.html', {'status': '재고가 부족합니다.'})
        
def display_orders_history(request):
    orders = Order.objects.filter(customer=request.user.customer)
    context = {'orders': orders}
    return render(request, 'order/order_list.html', context)

def display_order(request, pk):
    # if request.user.is_authenticated
    order = Order.objects.get(id=pk)
    return HttpResponse(order)

def delete_order(request, pk):
    order = Order.objects.get(id=pk)
    if request.method == 'POST':
        order.delete()
        return redirect('orders:display_orders')
    return render(request, 'order/order_delete.html', {'order': order})

order/templates/order/order.html
{% extends 'noncategory_base.html' %}

{% block content %}
<h4>{{ status }}</h4>
<a href="{% url 'logistics:main' %}">메인 화면으로</a>
{% endblock %}

order/templates/order/order_delete.html
{% extends 'customer_base.html' %}

{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'inquiry_support/question.css' %}">
{% endblock %}

{% block content %}
<title>주문 취소하기 customer</title>

<div class="container">
    <div class="title-container">
        {% with page_title="주문 취소하기" %}
            <h2>{{ page_title }}</h2>
        {% endwith %}
    </div>
    <div class="product-details">
        <p><strong>주문상품:</strong> {{ order.product.product_name }}</p>
        <p><strong>주문수량:</strong> {{ order.amount }}</p>
        <p><strong>총 금액:</strong> {{ order.price }}</p>
        {% if order.product.product_img %}
            <p><strong>이미지:</strong></p>
            <img src="{{ order.product.product_img.url }}" alt="주문 상품 이미지" class="product-img">
        {% endif %}
    </div>
    <form action="." method="post">
        {% csrf_token %}
        <button type="submit" class="btn-delete">주문 취소</button>
    </form>
    <button type="button" class="submit-button" onclick="window.location.href='{% url 'orders:display_orders' %}'">뒤로 가기</button>
</div>
{% endblock %}

order/templates/order/order_list.html
{% extends "customer_base.html" %}

{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'inquiry_support/list.css' %}">
{% endblock %}

{% block content %}
<div class="title-container">
    {% with page_title='상품 목록' %}
        <h2>{{ page_title }}</h2>
    {% endwith %}
</div>

<div>
    <table>
        <thead>
            <tr>
                <th>상품명</th>
                <th>가격</th>
                <th>수량</th>
                <th>총 금액</th>
                <th>배송 상태</th>
                <th>주문 취소</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.product.product_name }}</td>
                <td>{{ order.product.product_price }}</td>
                <td>{{ order.amount }}</td>
                <td>{{ order.price }}</td>
                <td>미정</td>
                <td class="product-buttons">
                    <a href="{% url 'orders:delete_order' order.id %}">
                        <button type="button">취소</button>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if orders|length == 0 %}
    <p class="empty-message">주문이 없습니다.</p>
    {% endif %}
</div>
{% endblock %}